tonbo-io/tonbo

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/question.md
update project name and link in issue template
=> chore: update issue template

src/lib.rs, src/stream/merge.rs, src/transaction.rs
Add limit operator to `MergeStream`
=> add limit on merge stream

src/fs/tokio_fs.rs, src/version/cleaner.rs, src/version/set.rs
ref: https://github.com/tonbo-io/tonbo/issues/123
=> fix: cleaner recover clean

src/compaction/mod.rs, src/lib.rs, src/transaction.rs, src/version/mod.rs, src/version/set.rs, tests/data_integrity.rs
ref: https://github.com/tonbo-io/tonbo/issues/36
=> chore: avoid `transaction_ts` from incrementing every time

src/fs/mod.rs, src/fs/tokio_fs.rs, src/lib.rs, src/option.rs, src/version/edit.rs, src/version/mod.rs, src/version/set.rs
ref: https://github.com/tonbo-io/tonbo/issues/129
=> feat: support VersionLog Snapshot

src/lib.rs, src/record/mod.rs, src/record/str.rs, src/stream/mem_projection.rs, src/stream/mod.rs, src/transaction.rs, tonbo_macros/src/lib.rs
ref: https://github.com/tonbo-io/tonbo/issues/25
=> feat: added `MemProjection` for projecting `TransactionScan` and `MutableScan`

src/compaction/mod.rs
https://github.com/tonbo-io/tonbo/pull/139#issuecomment-2334421662
=> test: add test for pr139

src/scope.rs, src/version/mod.rs
- add `Scope::meets_range` method to determine whether scope and range overlap
- skip SSTables that are not in range
=> feat: support skip scopes in scan

src/compaction/mod.rs, src/lib.rs
ref: https://github.com/tonbo-io/tonbo/issues/137
=> perf: `check_then_compaction` write lock optimization

Cargo.toml, examples/declare.rs, src/serdes/bytes.rs, src/serdes/mod.rs, tonbo_macros/src/data_type.rs, tonbo_macros/src/record.rs
ref: https://github.com/tonbo-io/tonbo/issues/88
=> feat: support DataType `bytes::Bytes`

src/version/edit.rs, src/version/set.rs
https://github.com/tonbo-io/tonbo/issues/142#issuecomment-2339819930  @crwen I implemented the content in the comment in this pr
=> fix: clear invalid `version_log`

src/lib.rs
Drop lock before send `CompactTask::Flush`
=> drop lock before flush

src/compaction/mod.rs, src/version/set.rs
ref: https://github.com/tonbo-io/tonbo/issues/152
=> fix: level slice are not ordered

src/version/set.rs
fix level slice ordered  problem and add test
=> fix level slice ordered

benches/common.rs, src/lib.rs, src/ondisk/sstable.rs, src/record/str.rs
`SSTable::get` will return the first data that is greater or equal than the key. But it should return the exact data that is equal to the key, otherwise return `None`
=> fix point query at sst

src/lib.rs, src/record/runtime/array.rs, src/record/runtime/column.rs, src/record/runtime/mod.rs, src/record/runtime/record.rs, src/record/runtime/record_ref.rs, src/serdes/list.rs, src/serdes/mod.rs
#179 
add int64, String, bool and Vec<u8> type for runtime schema
=> add more type for runtime schema

src/lib.rs
[`schema_recover`](https://github.com/tonbo-io/tonbo/blob/926874e6fc58349d3666c8b616f7b72a4c358fbd/src/lib.rs#L1588) does not enter the recover path now. This PR use `DB::new` to enter the schema recover path
=> chore: improve schema recover test

Cargo.toml, bindings/python/Cargo.toml, bindings/python/python/tonbo/__init__.pyi, bindings/python/src/db.rs, bindings/python/src/options.rs, src/inmem/mutable.rs, src/lib.rs, src/option.rs
=> add wal buffer

src/lib.rs, src/snapshot.rs, src/transaction.rs
ref: https://github.com/tonbo-io/tonbo/issues/206
=> chore: detach SnapShot from Transaction

src/compaction/mod.rs, src/inmem/mutable.rs, src/option.rs, src/stream/level.rs, src/version/cleaner.rs, src/version/mod.rs, src/version/set.rs
close  https://github.com/tonbo-io/tonbo/issues/213
=> refactor: replace all &FileId to FileId

README.md
=> chore: fix dead link in README.md

src/inmem/mutable.rs, src/lib.rs, src/version/set.rs, src/wal/mod.rs
support destroy: clean instance
=> feat: support destroy

.cargo/config.toml, Cargo.toml, src/record/runtime/schema.rs
- fix primary key index
- enable wasm_js under wasm32 and add rustflags
=> fix: wrong primary key index

bindings/python/src/error.rs, bindings/python/src/utils.rs, src/lib.rs, src/record/runtime/array.rs, src/record/runtime/record.rs, src/record/runtime/record_ref.rs, src/record/runtime/value.rs, src/transaction.rs, tests/wasm.rs
=> refactor: define `Value` with `ValueDesc`

guide/src/examples/datafusion.md
=> docs: fix a typo

src/fs/mod.rs
add truncate open option for writing sst
=> fix: add truncate open option for writing sst

benches/criterion/writes.rs, src/compaction/mod.rs, src/context.rs, src/lib.rs, src/snapshot.rs, src/transaction.rs, src/version/mod.rs
- #214
- projection on local storage in txn
=> Refactor: add context component

src/record/runtime/array.rs
`DynRecordImmutableArrays::get` returns `DynRecordRef` which means the inner values in columns(except the primary key) should be the type of `Option`.
Also, the number of columns should be the number of fields in schema
https://github.com/tonbo-io/tonbo/pull/313/files#diff-a0c3c7862ebea71debd399561857d74c963fa23d305cd5d3cffb1ab8e6795696R228-R231
=> fix: DynRecordImmutableArrays::get

.github/workflows/ci.yml, .github/workflows/ci_binding_python.yml, .github/workflows/ci_wasm.yml, .github/workflows/doc.yml, Cargo.toml, bindings/js/Cargo.toml, examples/datafusion.rs, parquet-lru/Cargo.toml, parquet-lru/src/dyn.rs, parquet-lru/src/foyer.rs, src/lib.rs, src/version/edit.rs, src/version/set.rs, src/wal/mod.rs, tests/data_integrity.rs, tests/wasm.rs
- add ci for s3
- bump arrow to v55
=> chore: add ci for s3

tests/macros_correctness.rs, tonbo_macros/src/record.rs
=> fix: record macros can not use without ref

src/record/runtime/array.rs, src/record/runtime/value.rs, tests/wasm.rs
- fix type error when use F32/F64 as primary key
- fix eq when compare `Option<T>`
- fix wasm tests
=> fix: DynRecord array primary key & value eq

src/record/runtime/record_ref.rs
`DynRecordRef::projection` should  set `None::<F32>`/`None::<F64>` as the none value for floating point number
=> fix: F32/F64 projection incorrect

bindings/python/Cargo.toml, bindings/python/src/datatype.rs, bindings/python/src/db.rs, bindings/python/src/fs.rs, bindings/python/src/lib.rs, bindings/python/src/stream.rs, bindings/python/src/transaction.rs, bindings/python/src/utils.rs
- bump pyo3 to v0.25
- replace pyo3-asyncio with pyo3-async-runtimes
=> chore: bump pyo3 to 0.25

guide/src/lsm_structure.md
Add a docs aboud a brief explanation of the lsm tree structure in tonbo.
=> docs: add brief explanation of lsm tree structure

src/compaction/leveled.rs
level_scan_ll should use level+1 instead of level's file.
=> fix: leveled compaction level_scan_ll fs is wrong

guide/src/lsm_structure.md
Add some path information of conponents of Tonbo.
=> docs: add path information of conponents of Tonbo

src/compaction/leveled.rs, src/compaction/mod.rs, src/scope.rs, src/version/edit.rs, src/version/set.rs
add file_size to `Scope` so that we can use scope to do more things.
=> add file_size to `Scope`

src/version/set.rs
While going through the code, I realized there wasn't too many comments + documentation which makes it a bit difficult for newer contributors to make sense of some parts of the codebase.
Added documentation to public functions and added some comments to clarify some logic
=> doc: Add docs for `VersionSet`

src/lib.rs
Clarify functionality in DB engine
=> doc: Add `DB` + `DBEngine` docs

src/compaction/mod.rs, src/ondisk/sstable.rs, src/version/set.rs
- Closes #.
Noticed CI was failing so added the missing file_size parameters. 
@ethe Visibility for SstableID needed to be changed because `CleanTag::Add` contains SsTableID which was more private
=> fix: Fix missing `file_size` for CI

src/compaction/mod.rs, src/inmem/immutable.rs, src/ondisk/scan.rs, src/record/key/timestamp.rs, src/record/runtime/record_ref.rs, src/record/runtime/value.rs, src/stream/level.rs, src/stream/package.rs, src/wal/mod.rs
Make clippy happy, remove all warning.
=> chore: make clippy happy

.github/workflows/ci.yml, .github/workflows/ci_binding_js.yml, .github/workflows/ci_binding_python.yml, .github/workflows/ci_wasm.yml
- Related to  #411 
Use rust-cache to to speed up ci
=> ci: add rust cache

benches/README.md, benches/common.rs, benches/read_bench.rs
This PR:
- Solve the identical DB issue
- Change the path to absolute path for S3
- Make clippy happy for bench code
Bench successfully in local env.
=> fix: fix read_bench bench code

src/record/dynamic/schema.rs
- Closes #.
Got confused with why schema wasn't out of index erroring, and forgot that schema is created with the _null and _ts field. Just used _deleted instead so we don't need to change in the future.
=> doc: Clarify schema creation

src/record/dynamic/value/encoding.rs
Replace custom encode_inner implementation with Key trait methods for consistency and maintainability. This change removes duplicate code and centralizes encoding logic.
- Closes #459 
Executed tasks: 
```
cargo test --package tonbo --lib -- record::dynamic::value::encoding::tests --show-output
cargo test --package tonbo --lib -- record::dynamic::value::tests --show-output
```
=> refactor(encoding): simplify value encoding by using Key trait

Cargo.lock, Cargo.toml
=> Bump `typed-arrow`

Cargo.lock, Cargo.toml, src/fs/manager.rs, src/fs/mod.rs, src/lib.rs
- Closes #.
Added a bulk of documentation and some code.
=> feat: Add Manager
