tonbo-io/tonbo

- .github/workflows/ci.yml
Compiling rocksdb is too slow to CI and actually it does not necessary, therefore remove it.
> enhancement: boost github action

- README.md
I've seen some Rust projects where comments like struct and fn are usually ///, and comments inside methods are //. I think this is a better way to distinguish them.
> chore: annotation normalization

- src/serdes/mod.rs
- Implemented a simple struct `TestStruct` that implements `Encode` and `Decode` traits.
- Added async encode and decode methods for `TestStruct`.
- Created a test to verify encoding and decoding functionality.
> feat: Add test for Encode and Decode traits

- Cargo.toml
- src/compaction/mod.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/option.rs
- src/record/mod.rs
- src/record/str.rs
- src/stream/merge.rs
- src/stream/package.rs
- src/trigger.rs
- tonbo_macro/src/lib.rs
Implemented a `size` method for `Record` and added a trigger mechanism (`Trigger`, `TriggerFactory`) to handle dynamic item insertion and manage memory efficiently. Adjusted related stream implementations and updated dependency path for `tonbo_marco`.
> Add size calculation method and trigger mechanism

- src/lib.rs
- tonbo_macro/src/lib.rs
> fix: re-export `tonbo_macro::KeyAttributes`

- src/inmem/immutable.rs
- src/inmem/mutable.rs
- src/ondisk/arrows.rs
- src/transaction.rs
#93 
The result is not correct when using `Bound::Exclude` and `Bound::Include` in `Transaction::scan`. 
This PR fixes the issue:
- fix range filter in disk table
- fix range bound in memory table
> fix range query

- src/lib.rs
- src/option.rs
- src/transaction.rs
Some links didnt work, like the `DbOption` in the doc of `DB::new`. https://docs.rs/tonbo/0.1.0/tonbo/struct.DB.html
This PR should fix the problem.
> fix: doc links

- src/compaction/mod.rs
- src/lib.rs
- src/stream/merge.rs
- src/stream/package.rs
- src/transaction.rs
- src/trigger.rs
related to #103 
This pr add a filter logic on `MergeStream::poll_next` to filter the data that has larger timestamp.
> fix: add ts filter on MergeStream

- src/compaction/mod.rs
- src/lib.rs
- src/transaction.rs
Introduces a new `Flush` variant to the `CompactTask` enum, which includes an optional `oneshot::Sender` for notifying task completion. Updates the compaction logic to handle this new task variant and sends the notification upon completion. Adds error handling for potential transmission failures in the compaction process.
> feat: add flush compaction task with oneshot notification

- src/inmem/immutable.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/transaction.rs
#126 
break point query into memory query and  disk query: return immediately, if data is found in memory table. Otherwise search on disk files
> point query optimization

- src/transaction.rs
- src/version/mod.rs
https://github.com/tonbo-io/tonbo/pull/132/files#diff-ca40038cc1220f9b25a1e0808df841d4b5fafcd936bfd43b9f8e39b8719a66c5R298
Before pr: https://github.com/tonbo-io/tonbo/pull/122, transaction_ts can only be incremented by creating a transaction. After pr: https://github.com/tonbo-io/tonbo/pull/125, you need to use `increase_ts`
> fix: resolve merge & `test::transaction_get`

- src/compaction/mod.rs
`LevelStream::new` accepts a start index and a end index, which are both closed. So `this_level_scopes` should return a right-closed index
https://github.com/tonbo-io/tonbo/blob/b9b02a83ecca3513f728ca7a71052a7b9ec7c0ef/src/stream/level.rs#L76
> fix level scope index

- src/compaction/mod.rs
fix manually flush panic when mutable is empty(due to channel dropping before sending)
> fix oneshot channel dropped while mutable is empty

- .github/workflows/ci.yml
when the pr is merged, the benchmark action will make an error when commenting because the pr cannot be found.
> ci: only run benchmark in pr event

- tonbo_macros/src/record.rs
`arrow::array::Array` will define multiple times when there are more than two `Option` attributes
> fix array define multiple times

- examples/datafusion.rs
Added support for executing SQL queries using DataFusion's parser and physical plan execution. This enhancement allows querying the "music" table with SQL statements, improving flexibility and functionality.
> feat: enable SQL query support in datafusion example

- examples/datafusion.rs
This pull request includes a change to the SQL query and the execution order in the `main` function of the `examples/datafusion.rs` file. The most important changes are as follows:
* Modified the SQL query from `select * from music` to `select id from music` to limit the columns retrieved. (`examples/datafusion.rs`, [examples/datafusion.rsL240-R245](diffhunk://#diff-8465dc0f99d36da97211853d2b789fe53641b9b2b372ef10a063dad79e16d571L240-R245))
* Changed the execution order by combining the logical plan execution and table retrieval into a single step. (`examples/datafusion.rs`, [examples/datafusion.rsL240-R245](diffhunk://#diff-8465dc0f99d36da97211853d2b789fe53641b9b2b372ef10a063dad79e16d571L240-R245))
> fix: modify SQL query and streamline DataFrame execution

- Cargo.toml
- benches/common.rs
- benches/criterion/writes.rs
- src/compaction/mod.rs
- src/fs/manager.rs
- src/fs/mod.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/ondisk/sstable.rs
- src/option.rs
- src/stream/level.rs
- src/transaction.rs
- src/version/cleaner.rs
- src/version/mod.rs
- src/version/set.rs
bug: 
- Compaction triggered by flush will not return tx after an error occurs.
- SSTable does not enable `append` when opening a file
- Fix level inconsistency in `Compactor::build_tables`
- Remove the meaningless `StoreManger::create_dir_all`
todo:
- S3 remote connection writing performance is slow
- The problem occurs in Cleaner's RecoverClean. Already deleted Tables may be deleted repeatedly (redundant deletion). This is expected.
> fix: `DbOption::table_path` with level

- bindings/python/pyproject.toml
- bindings/python/tests/conftest.py
- bindings/python/tests/test_write_async_benchmark.py
- bindings/python/tests/test_write_benchmark.py
Add write test for python binding
Here are the results of the writing tests in my machine:
write 10000 records:
```
DuckDB took 20.72643 seconds to insert 10000 records
SQLite took 0.02475 seconds to insert 10000 records
SQLite with autocommit took 5.43819 seconds to insert 10000 records
Tonbo took 0.89315 seconds to insert 10000 records
Tonbo without transaction took 1.68304 seconds to insert 10000 records
Tonbo without transaction write batch took 0.75287 seconds to insert 10000 records
```
benchmark for 10000 inserts(compare mode):
```bash
BENCH=true pytest tests/test_write_benchmark.py --benchmark-compare
```
```
------------------------------------------------------------------------------- benchmark 'autocommit': 3 tests --------------------------------------------------------------- …
```
> add write benchmark

- bindings/python/README.md
- bindings/python/tests/test_db.py
- src/record/runtime/column.rs
Now name attribute is not encoded into file, which will result in getting wrong answer after db recovery . This PR encode name attribute to file and add recovery test for python binding
> chore: encode column name attribute

- src/compaction/mod.rs
- src/inmem/mutable.rs
- src/scope.rs
Related issue: https://github.com/tonbo-io/tonbo/issues/212
Minor refactor to replace the Ulid to FileId
> Minor refactor: replace Ulid to FileId

- src/lib.rs
- src/snapshot.rs
- src/transaction.rs
Related issue: https://github.com/tonbo-io/tonbo/issues/135
Also fixed a small warning by removing the unnecessary `mut`
> Isolate range param lifetime from scan lifetime

- src/compaction/mod.rs
- src/fs/mod.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/scope.rs
- src/version/cleaner.rs
- src/version/edit.rs
- src/version/set.rs
- src/wal/mod.rs
Replaces all `FileId::new` with `generate_file_id`.
Fixes: #146
> chore: replace FileId::new

- Cargo.toml
- bindings/python/Cargo.toml
- src/lib.rs
- src/version/set.rs
- src/wal/mod.rs
- tests/wasm.rs
Since fusio has changed close semantics, tonbo should change, too.
- remove log in VersionInner
- open log file before using
> Refactor: remove log in VersionInner

- src/record/runtime/array.rs
In `PackageStream`, the record in`DynRecordImmutableArrays::push` has been projected, which may cause inconsistencies between the data and the schema. So, we should set the value to default value instead of `None`.
> fix: replace null with default in record builder

- src/lib.rs
- tonbo_macros/src/record.rs
re-export `fusio_log::Encode` and `fusio_log::Decode` to eliminate dependence on `fusio_log`
> refactor: re-export `fusio_log::Encode/Decode`

- README.md
- bindings/js/src/transaction.rs
- bindings/python/src/transaction.rs
- examples/datafusion.rs
- examples/declare.rs
- src/lib.rs
- src/snapshot.rs
- src/transaction.rs
- tests/wasm.rs
ref #133 
Use field names for projection instead of using indices
```rust
let name = "Alice".into();
let upper = "Bob".into();
let mut scan = txn
.scan((Bound::Included(&name), Bound::Excluded(&upper)))
.projection(vec!["name, "age"])
.take()
.await
.unwrap();
```
> refactor: project by name

- bindings/js/Cargo.toml
- bindings/js/src/fs.rs
- bindings/js/src/options.rs
- bindings/python/Cargo.toml
- bindings/python/src/fs.rs
- bindings/python/src/options.rs
- src/option.rs
If we want to use tonbo, we have to import fusio, too. This PR re-export fusio structures so that we can use tonbo like this:
```toml
tonbo = { version = "0.3.1",  features = [] }
```
> re-export fusio::FsOptions and AwsCredential

- src/compaction/mod.rs
- src/lib.rs
- src/version/set.rs
fix compile error cause by #295
> fix: compile error

- src/record/runtime/array.rs
Append null to `ArrayBuilder` if record is null and column is nullable.
> fix: append null if nullable

- examples/dynamic.rs
- src/lib.rs
- src/record/runtime/array.rs
- src/record/runtime/mod.rs
- src/record/runtime/record.rs
- src/record/runtime/schema.rs
use macros to simplify the usage of  `DynSchema` and `DynRecord`:
```rust
let schema = dyn_schema!(
("foo", String, false),
("bar", Int32, true),
("baz", UInt64, false),
0
);
let record = dyn_record!(
("foo", String, false, "hello".to_owned()),
("bar", Int32, true, 1_i32),
("baz", UInt64, false, 2_u64),
0
);
```
> add macros to simplify the usage of `DynRecord`

- bindings/js/src/utils.rs
- bindings/python/src/utils.rs
- examples/declare.rs
- src/lib.rs
- src/record/key/mod.rs
- src/record/key/num.rs
- src/record/mod.rs
- src/record/runtime/array.rs
- src/record/runtime/mod.rs
- src/record/runtime/record.rs
- src/record/runtime/record_ref.rs
- src/record/runtime/value.rs
- tests/macros_correctness.rs
- tonbo_macros/src/data_type.rs
- tonbo_macros/src/record.rs
Introduce `F32`/`F64` type to support float type. The behaviors are aligned to arrow.
**Note**: 
- In IEEE, `NAN !=  NAN`, but in arrow `NAN == NAN`. Our behavior is aligned to arrow
- Python and WASM bindings are not implemented
> feat: support float type

- src/inmem/immutable.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/ondisk/sstable.rs
- src/record/option.rs
- src/record/runtime/array.rs
- src/record/test.rs
- src/stream/mod.rs
- src/stream/record_batch.rs
- src/timestamp/mod.rs
- src/timestamp/timestamped.rs
- src/transaction.rs
- src/version/mod.rs
- src/wal/log.rs
- src/wal/mod.rs
- tests/macros_correctness.rs
- tonbo_macros/src/record.rs
As wrapper types, the name of `Timestamped` and `TimestampedRef` is too long, rename to make it shorter.
> refactor: rename Timestamped to Ts, TimestampedRef to TsRef

- src/version/set.rs
In #295 , we open manifest file with truncate option because only truncate mode is supported by S3.
But when open file with truncate mode, the content will be clear. So I think we can remove the truncate option for now. For S3 case, we can wait for #327 . If you think this is ok I'll pull another PR to fix this problem in wal.
> fix: open version log clear content

- src/compaction/leveled.rs
- src/option.rs
I think `is_threshold_exceeded_major` make sense for only level compaction. So it's better to move it to `LevelCompactor`
> refactor: move `is_threshold_exceeded_major` to `LevelCompactor`

- .github/ISSUE_TEMPLATE/feature-request.yml
I do not feel that an alternative or reference should be required. 
- Made it so alternative or reference is not longer required.
- Reworded some of the points
> fix: Remove required input for issue template

- src/version/set.rs
When calling `VersionSet::new()` we do not need to call `apply_edits()` if `edits.is_empty()`.
> feat: Fast path for `apply_edits`

- src/compaction/error.rs
- src/compaction/mod.rs
- src/lib.rs
`CompactionError` can be missed in the midst of all the files. We can move this into its own file in the compaction folder
> refactor: Move `CompactionError` into error file

- src/version/cleaner.rs
In #384, the test for cleaning files will possibly fail. We bump the time to remove the likelihood of ci failing.
> fix: Fix non-deterministic test when cleaning files

- src/compaction/leveled.rs
- src/ondisk/sstable.rs
- src/version/cleaner.rs
- src/version/set.rs
While reading throught the codebase I noticed that deleted SSTable identification was a little unclear (mostly that the usize was for the level). I added a new struct to replace this. 
```rust 
pub struct SsTableID {
// File id for the SStable
file_id: FileId,
// The level for which the SSTable is located
level: usize,
}
```
> refactor: Use `SsTableID` for identification

- Cargo.toml
- src/version/set.rs
When compaction generates `VersionSet::Add` SST operations, many of these operations will be consecutive. To avoid doing a binary search for every element + insert (shifts all elements) we can instead batch all 'add' operations and check if consecutive ssts can be inserted together.
> feat: Optimize binary search for `VersionEdit::Add`

- src/compaction/leveled.rs
Closes #158.
If we have manual compaction on level 0 and level 1 is empty. Due to level 0 SSTs being unsorted we can self compact level 0 SSTs that fall in the key range.
The logic in `this_level_scopes` was incorrect as it would do a linear search and stop when a SST didnt fall in the range. However level 0 SSTs are unsorted and this would lead to incorrect behaviour. 
Instead I changed it so that it would do a linear search over all the SSTs and append every SST that fell in the range.
Manual compaction will now be used even if threshold is not met.
> fix: Fix manual compaction logic

- bindings/python/src/db.rs
- src/inmem/mutable.rs
- src/lib.rs
- src/transaction.rs
closes #392 
I ran existing tests but nothing is broken by these changes, any pointer as to where to add appropriate tests is appreciated.
P.S. re-reading the diffs, I feel like the current bool version is clearer, especially at call sites
> refactor: return enum for MutableMemTable

- src/compaction/leveled.rs
- src/inmem/immutable.rs
- src/lib.rs
- src/ondisk/sstable.rs
- src/record/test.rs
- src/trigger.rs
- tests/trybuild.rs
- Move `get_test_record_batch` from `src/lib.rs` test module to `src/record/test .rs` under `#[cfg(all(test, feature = "tokio"))]`
- Update imports in `src/ondisk/sstable.rs` tests to use `crate::record::test::{ get_test_record_batch, Test}`
- Introduce `test_items<I>(range: I) -> impl Iterator<Item = Test>` in `src/reco rd/test.rs`
- Refactor all call sites in `src/lib.rs` tests to use `test_items(0u32..N)` ins tead of local `test_items()` and slicing
- Remove old helpers from `src/lib.rs` and clean unused imports
- Clippy clean and all tests pass
> test: centralize record test helpers and refactor generators

- guide/src/contribution/composite_primary_keys.md
- src/compaction/leveled.rs
- src/lib.rs
- src/ondisk/arrows.rs
- src/ondisk/sstable.rs
- src/record/dynamic/value/mod.rs
- src/record/key/composite/mod.rs
- src/record/key/datetime.rs
- src/record/key/mod.rs
- src/record/key/num.rs
- src/record/key/str.rs
- src/record/key/timestamp.rs
- src/stream/level.rs
- src/version/mod.rs
- Key API: replace `Key::to_arrow_datum` with `Key::to_arrow_datums` to supportmulti-component keys; update all builtin `Key` impls (ints/floats/string/date/time/timestamp/dynamic `Value`) to return a single-element Vec for single-PK types.
- Composite key showcase: add `Key2`/`Key2Ref` under `#[cfg(test)]` with `Encode`/`Decode`, `Ord`, `Hash`, `Key`/`KeyRef`; round-trip and ordering tests included.
- Parquet scan filtering: implement lexicographic composite range predicates in`get_range_filter` using `eq/gt/gt_eq/lt/lt_eq` with `and_kleene`/`or_kleene`; retain `_ts` upper-bound predicate.
- Scan plumbing: thread `pk_indices` through `SsTable::{get,scan}`, `Version::{query,streams,table_query}`, and `LevelStream`; update test callers. Build fixed projections as `[0, 1] ∪ pk_indices` in …
> feat(core)!: composite PK plumbing, Key API change, and Arrow filters

- benches/common.rs
Add type hints `TokioExecutor` for txn in bench code
> fix: add type hints for txn in bench
